import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"
import { periodLabel } from "@/api/cgt_filter_params"
import type { StoredCgtReport } from "./stored_reports"
import type { TaxBandResult } from "@/bindings/TaxBandResult"
import type { CgtRealizedEvent } from "@/bindings/CgtRealizedEvent"

const styles = StyleSheet.create({
  page: { padding: 36, fontFamily: "Helvetica", fontSize: 10, color: "#1a1a1a" },
  h1: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  h2: { fontSize: 13, fontWeight: 700, marginTop: 18, marginBottom: 6 },
  meta: { fontSize: 9, color: "#555" },
  block: { marginBottom: 8 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 2 },
  label: { color: "#444" },
  value: { fontFamily: "Helvetica" },
  bold: { fontWeight: 700 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f2f2f2",
    borderBottom: "1pt solid #d4d4d4",
    paddingVertical: 4,
    paddingHorizontal: 4,
    fontSize: 9,
    fontWeight: 700,
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1pt solid #eee",
    paddingVertical: 3,
    paddingHorizontal: 4,
    fontSize: 9,
  },
  disposalBlock: {
    marginBottom: 14,
    paddingBottom: 8,
    borderBottom: "1pt solid #ccc",
  },
  disposalHeader: { fontSize: 11, fontWeight: 700, marginBottom: 4 },
  footnote: { fontSize: 8, color: "#666", marginTop: 6 },
  warning: {
    marginTop: 8,
    padding: 8,
    backgroundColor: "#fff4e5",
    border: "1pt solid #f0b37e",
    borderRadius: 3,
  },
  warningText: { fontSize: 9, color: "#7a4f01" },
  footer: {
    position: "absolute",
    left: 36,
    right: 36,
    bottom: 18,
    fontSize: 8,
    color: "#888",
    textAlign: "center",
  },
})

interface CgtPdfDocumentProps {
  report: StoredCgtReport
}

export function CgtPdfDocument({ report }: CgtPdfDocumentProps) {
  const { filters, response, generatedAt } = report
  const cur = response.summary.base_currency
  // The UTR is the primary identity field on every SA108 page, so it goes in the
  // running footer. Omitted entirely when absent rather than printed empty — a
  // blank "UTR:" label on a tax document reads as a missing value.
  const utrPart = report.utr ? ` · UTR: ${report.utr}` : ""
  const footerPrefix = `Generated by fynance · ${periodLabel(filters.period)} · ${new Date(generatedAt).toLocaleString()}${utrPart}`
  const renderFooter = ({
    pageNumber,
    totalPages,
  }: {
    pageNumber: number
    totalPages: number
  }) => `${footerPrefix} · Page ${pageNumber} of ${totalPages}`
  // Disposals the engine could not match to any acquisition are assigned a zero
  // cost basis, so 100% of their proceeds becomes gain. That almost always means
  // the acquisition ledger is incomplete (e.g. RSU vests booked net instead of
  // gross); surface it loudly rather than letting an overstated gain pass silently.
  const unmatched = response.realized_events.filter((e) => e.rule_applied === "Unmatched")
  const unmatchedProceeds = unmatched.reduce(
    (sum, e) => sum + Number.parseFloat(e.proceeds),
    0,
  )
  // The tax computation is the server's. It is present only when the report was
  // generated for a whole UK tax year, because tax is only defined for one.
  const tax = response.tax ?? null
  const taxYear = tax?.tax_year ?? null
  // Only bands that actually bear tax are worth a row; a band fully covered by
  // losses or the allowance would print as a £0.00 line that reads like an error.
  const taxableBands = (tax?.bands ?? []).filter((b) => Number.parseFloat(b.taxable) > 0)
  // Whether the year splits across more than one *period* (as 2024-25 does, at
  // 30 October 2024). Decides whether band labels need to name their date range:
  // with a single period, "Gains from 6 Apr 2024 @ 24%" is noise.
  const multipleBandPeriods = new Set(taxableBands.map((b) => b.valid_from)).size > 1

  // Pool workings support THIS return's disposals, so only show pools for symbols
  // actually disposed in the period — not every holding still in the global pool.
  const disposedSymbols = new Set(response.realized_events.map((e) => e.symbol))
  const poolRows = response.pools.filter(
    (p) => Number.parseFloat(p.current_shares) > 0 && disposedSymbols.has(p.symbol),
  )
  return (
    <Document
      title={`Capital Gains Tax Report — ${periodLabel(filters.period)}`}
      author="fynance"
    >
      <Page size="A4" style={styles.page}>
        <Text style={styles.footer} fixed render={renderFooter} />
        <Text style={styles.h1}>Capital Gains Tax Report</Text>
        <Text style={styles.meta}>
          {periodLabel(filters.period)} · Generated {new Date(generatedAt).toLocaleString()}
        </Text>

        <Text style={styles.h2}>Summary</Text>
        <View style={styles.block}>
          <SummaryRow label="Number of disposals" value={String(response.realized_events.length)} />
          <SummaryRow label="Disposal proceeds" value={fmt(response.summary.total_proceeds, cur)} />
          <SummaryRow
            label="Allowable costs (including purchase price)"
            value={fmt(response.summary.total_allowable_costs, cur)}
          />
          <SummaryRow
            label="Gains in the year, before losses"
            value={fmt(response.summary.total_gains, cur)}
          />
          <SummaryRow label="Losses in the year" value={fmt(response.summary.total_losses, cur)} />
          <SummaryRow
            label="Net gain/loss in the year"
            value={fmt(response.summary.net_gain_loss, cur)}
            bold
          />
          {tax && (
            <>
              {Number.parseFloat(tax.current_year_losses_applied) > 0 && (
                <SummaryRow
                  label="Losses in the year, set against gains"
                  value={`-${fmt(tax.current_year_losses_applied, cur)}`}
                />
              )}
              {Number.parseFloat(tax.brought_forward_losses_applied) > 0 && (
                <>
                  <SummaryRow
                    label="Brought-forward losses used"
                    value={`-${fmt(tax.brought_forward_losses_applied, cur)}`}
                  />
                  {/*
                    On the filed document as well as on screen: an unqualified
                    brought-forward figure overstates the relief available.
                  */}
                  <Text style={styles.footnote}>
                    Losses carry forward only if claimed within four years of the end of the
                    year they arose, and only the part left after that year&rsquo;s own gains
                    carries at all. Check against your filed returns.
                  </Text>
                </>
              )}
              <SummaryRow
                label={`Annual Exempt Amount (${taxYear})`}
                value={`-${fmt(tax.aea_applied, cur)}`}
              />
              <SummaryRow
                label="Taxable gain after losses and allowance"
                value={fmt(tax.taxable_gain, cur)}
                bold
              />
            </>
          )}
        </View>
        <Text style={styles.footnote}>
          {tax
            ? `Computed for tax year ${taxYear} from the stored tax configuration and your recorded figures. Disposals made outside this app are not included.`
            : "Figures are pre-relief; choose a tax year to apply the Annual Exempt Amount and compute tax."}{" "}
          Foreign-currency disposals are converted to {cur} at the configured exchange rate.
        </Text>

        {unmatched.length > 0 && (
          <View style={styles.warning}>
            <Text style={styles.warningText}>
              ⚠ {unmatched.length} disposal{unmatched.length === 1 ? "" : "s"} (
              {fmt(String(unmatchedProceeds), cur)} of proceeds) could not be matched to
              any acquisition and were treated as 100% gain (zero cost basis). This
              usually means acquisition events (vests or buys) are missing or understated,
              so the gain above is overstated. Review the ledger before filing.
            </Text>
          </View>
        )}

        {tax && taxableBands.length > 0 && (
          <View style={styles.block}>
            <Text style={styles.h2}>Capital Gains Tax</Text>
            {taxableBands.map((b) => (
              <SummaryRow
                key={`${b.valid_from}-${b.rate_kind}`}
                label={bandLabel(b, multipleBandPeriods)}
                value={fmt(b.tax, cur)}
              />
            ))}
            <SummaryRow label="Capital Gains Tax due" value={fmt(tax.tax_due, cur)} bold />
            <Text style={styles.footnote}>
              Estimate only, not tax advice. Gains are charged at the rate in force on the
              date of each disposal, and losses and the Annual Exempt Amount are set against
              the most heavily taxed gains first. Confirm with your accountant before filing.
            </Text>
          </View>
        )}

        {tax && Number.parseFloat(tax.total_gains) > 0 && taxableBands.length === 0 && (
          <Text style={styles.footnote}>
            No Capital Gains Tax due for {taxYear}: the gains are covered by losses and the
            Annual Exempt Amount.
          </Text>
        )}

        {response.symbol_summaries.length > 0 && (
          <>
            <Text style={styles.h2}>Per-symbol breakdown</Text>
            <View style={styles.tableHeader}>
              <Text style={{ flex: 1.5 }}>Symbol</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>Proceeds</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>Costs</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>Net gain/loss</Text>
            </View>
            {response.symbol_summaries.map((s) => (
              <View key={s.symbol} style={styles.tableRow}>
                <Text style={{ flex: 1.5 }}>{s.symbol}</Text>
                <Text style={{ flex: 1, textAlign: "right" }}>{fmt(s.total_proceeds, cur)}</Text>
                <Text style={{ flex: 1, textAlign: "right" }}>
                  {fmt(s.total_allowable_costs, cur)}
                </Text>
                <Text style={{ flex: 1, textAlign: "right" }}>{fmt(s.net_gain_loss, cur)}</Text>
              </View>
            ))}
          </>
        )}
      </Page>

      {response.realized_events.length > 0 && (
        <Page size="A4" style={styles.page} wrap>
          <Text style={styles.footer} fixed render={renderFooter} />
          <Text style={styles.h1}>Capital Gains Disposal Summary</Text>
          <Text style={styles.meta}>
            One block per matched leg. Mirrors the SA108 supplementary workings page.
          </Text>
          {response.realized_events.map((e, idx) => (
            <DisposalBlock key={`${e.disposal_id}-${idx}`} event={e} currency={cur} />
          ))}
        </Page>
      )}

      {poolRows.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.footer} fixed render={renderFooter} />
          <Text style={styles.h1}>S104 Pool Workings</Text>
          <Text style={styles.meta}>
            Average-cost pool for each symbol disposed in this period, supporting the
            costs above.
          </Text>
          <View style={styles.tableHeader}>
            <Text style={{ flex: 1.5 }}>Symbol</Text>
            <Text style={{ flex: 1, textAlign: "right" }}>Current shares</Text>
            <Text style={{ flex: 1.4, textAlign: "right" }}>Total allowable expenditure</Text>
            <Text style={{ flex: 1.2, textAlign: "right" }}>Avg cost / share</Text>
          </View>
          {poolRows.map((p) => (
            <View key={p.symbol} style={styles.tableRow}>
              <Text style={{ flex: 1.5 }}>{p.symbol}</Text>
              <Text style={{ flex: 1, textAlign: "right" }}>{fmtShares(p.current_shares)}</Text>
              <Text style={{ flex: 1.4, textAlign: "right" }}>
                {fmt(p.total_allowable_expenditure, cur)}
              </Text>
              <Text style={{ flex: 1.2, textAlign: "right" }}>
                {fmt(p.average_cost_per_share, cur)}
              </Text>
            </View>
          ))}
        </Page>
      )}
    </Document>
  )
}

function fmtShares(qty: string): string {
  const n = Number.parseFloat(qty)
  if (!Number.isFinite(n)) return "—"
  return n.toLocaleString("en-GB", { minimumFractionDigits: 0, maximumFractionDigits: 4 })
}

function DisposalBlock({
  event,
  currency,
}: {
  event: CgtRealizedEvent
  currency: string
}) {
  const acquisition = event.matches[0]?.acquisition_date ?? null
  return (
    <View style={styles.disposalBlock} wrap={false}>
      <Text style={styles.disposalHeader}>
        {event.symbol} — disposed {event.disposal_date.slice(0, 10)} · {event.rule_applied}
      </Text>
      <View style={styles.row}>
        <Text style={styles.label}>Date of acquisition</Text>
        <Text style={styles.value}>{acquisition ?? "Not matched"}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Date of disposal</Text>
        <Text style={styles.value}>{event.disposal_date.slice(0, 10)}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Quantity</Text>
        <Text style={styles.value}>{fmtShares(event.quantity)}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Disposal proceeds</Text>
        <Text style={styles.value}>{fmt(event.proceeds, currency)}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Acquisition cost</Text>
        <Text style={styles.value}>{fmt(event.cost_basis, currency)}</Text>
      </View>
      <View style={styles.row}>
        <Text style={[styles.label, styles.bold]}>Gain or (Loss)</Text>
        <Text style={[styles.value, styles.bold]}>{fmt(event.gain_loss, currency)}</Text>
      </View>
    </View>
  )
}

function SummaryRow({ label, value, bold = false }: { label: string; value: string; bold?: boolean }) {
  return (
    <View style={styles.row}>
      <Text style={[styles.label, bold ? styles.bold : {}]}>{label}</Text>
      <Text style={[styles.value, bold ? styles.bold : {}]}>{value}</Text>
    </View>
  )
}

function fmtBandDate(iso: string): string {
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
  const [y, m, d] = iso.split("-")
  return `${Number(d)} ${months[Number(m) - 1]} ${y}`
}

/**
 * Label for one rate band row.
 *
 * The rate comes from the server as a fraction, so it is rendered as a
 * percentage here and nowhere else. `multiplePeriods` is why the date range is
 * conditional: naming it is essential when a year splits (2024-25 does, on 30
 * October 2024) and is noise when it does not.
 *
 * The band kind is named too. A period contributes up to two rows — the slice
 * of its gains covered by basic-rate income headroom, and the rest at the
 * higher rate — and both carry the same `valid_from`. Labelled by date alone
 * they read as two rows for the same period with no stated reason to differ,
 * which on a document someone files looks like a duplicate or a date error
 * rather than the basic/higher split it actually is.
 */
function bandLabel(band: TaxBandResult, multiplePeriods: boolean): string {
  const pct = `${(Number.parseFloat(band.rate) * 100).toFixed(0)}%`
  const kind = band.rate_kind === "basic" ? "basic rate" : "higher rate"
  if (!multiplePeriods) return `Taxable gains, ${kind} @ ${pct}`
  return `Gains from ${fmtBandDate(band.valid_from)}, ${kind} @ ${pct}`
}

const CURRENCY_SYMBOLS: Record<string, string> = {
  GBP: "£",
  USD: "$",
  EUR: "€",
  NGN: "₦",
}

function fmt(amount: string, currency: string): string {
  const n = Number.parseFloat(amount)
  if (!Number.isFinite(n)) return "—"
  const symbol = CURRENCY_SYMBOLS[currency] ?? `${currency} `
  const abs = Math.abs(n).toLocaleString("en-GB", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
  return n < 0 ? `-${symbol}${abs}` : `${symbol}${abs}`
}
