// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountHoldingValue } from "./AccountHoldingValue";

/**
 * One period in the `GET /api/holdings/account-history` response: the account's
 * total value and the per-symbol breakdown at that period end (preferred currency).
 */
export type AccountHoldingHistoryRow = { 
/**
 * Period label: "YYYY-MM" for monthly, "YYYY-Qn" for quarterly, "YYYY" for yearly.
 */
period: string, total: string, values: Array<AccountHoldingValue>, };
