// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Point-in-time account balance derived from SUM(holdings.value).
 * Used by `GET /api/portfolio/balances` (non-summary mode).
 */
export type AccountSnapshot = { as_of: string, account_id: string, balance: string, currency: string, };
