// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from "./AccountType";

export type Account = { id: string, name: string, institution: string, type: AccountType, currency: string, balance: string | null, balance_date: string | null, is_active: boolean, notes: string | null, 
/**
 * JSON array of profile IDs, e.g. `["alex", "sam"]`. Required: there is no
 * implicit default profile, so this must name at least one existing profile.
 */
profile_ids: Array<string>, 
/**
 * Set in portfolio responses to indicate whether the carried-forward
 * balance is stale (snapshot > 45 days before the query date).
 * Absent (`None`) in non-portfolio contexts.
 */
is_stale: boolean | null, 
/**
 * True for account types that count toward available (liquid) wealth.
 * Derived from account_type at query time; never stored in the DB.
 */
is_available: boolean, };
