// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Value of one holding at a period end, converted to the preferred currency.
 */
export type AccountHoldingValue = { symbol: string, value: string, };
