// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable metadata for one holding line in an account's history chart.
 * Used by `GET /api/holdings/account-history`.
 */
export type AccountHoldingSeries = { symbol: string, name: string, short_name: string | null, };
