// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Broad asset class used for portfolio grouping.
 */
export type AssetClass = "Investments" | "Pension" | "Property" | "Cash";
