// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which Anthropic credential the parse pipeline should use. The actual model,
 * prompts, tools, and output are identical across all variants; only the
 * authentication (and therefore billing) differs.
 */
export type AuthSource = "auto" | "subscription" | "api_key";
