// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which bank's dialect a CSV file came from. Used for bookkeeping / display
 * only; the import path never branches on this value.
 */
export type BankFormat = "monzo" | "revolut" | "lloyds" | "unknown";
