// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One slice of a portfolio breakdown (by type, institution, or asset class).
 */
export type BreakdownItem = { label: string, value: string, percentage: number, };
