// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-month override for a standing budget.
 */
export type BudgetOverride = { month: string, category: string, amount: string, };
