// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A standing budget (old model). Kept for CLI backward compatibility.
 */
export type Budget = { month: string, category: string, amount: string, };
