// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the `GET /api/budget/:month` response.
 */
export type BudgetRow = { category: string, 
/**
 * Effective budget for this month (standing or override). Null if not set.
 */
budgeted: string | null, 
/**
 * Actual spend this month (absolute value of negative transactions).
 */
actual: string, 
/**
 * `actual / budgeted * 100`. Null when `budgeted` is null or zero.
 */
percent: number | null, };
