// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CgtRealizedEvent } from "./CgtRealizedEvent";
import type { CgtSummary } from "./CgtSummary";
import type { S104PoolState } from "./S104PoolState";

export type CapitalGainsResponse = { summary: CgtSummary, realized_events: Array<CgtRealizedEvent>, pools: Array<S104PoolState>, };
