// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CgtDisposalGroup } from "./CgtDisposalGroup";
import type { CgtRealizedEvent } from "./CgtRealizedEvent";
import type { CgtSummary } from "./CgtSummary";
import type { S104PoolState } from "./S104PoolState";
import type { SymbolSummary } from "./SymbolSummary";
import type { TaxComputation } from "./TaxComputation";

export type CapitalGainsResponse = { summary: CgtSummary, symbol_summaries: Array<SymbolSummary>, realized_events: Array<CgtRealizedEvent>, 
/**
 * One row per actual sale — `realized_events` rolled up by `(symbol,
 * disposal_date)`. See [`CgtDisposalGroup`] for why this exists
 * alongside, not instead of, the granular rows.
 */
disposal_groups: Array<CgtDisposalGroup>, pools: Array<S104PoolState>, 
/**
 * The tax computation, present only when the request named a `tax_year`.
 * Absent means "not asked for", never "no tax due" — a nil tax bill is a
 * present computation whose `tax_due` is zero.
 */
tax: TaxComputation | null, };
