// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the `GET /api/cash-flow` response.
 */
export type CashFlowMonth = { 
/**
 * Period label: "YYYY-MM", "YYYY-Qn", or "YYYY".
 */
month: string, income: string, spending: string, };
