// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvestmentMetrics } from "./InvestmentMetrics";

/**
 * Category-type-driven cash summary for the portfolio "Income, Spending &
 * Investments" card. Returned by `GET /api/budget/cash-summary`, range-aware.
 */
export type CashSummaryResponse = { preferred_currency: string, 
/**
 * Sum of income_taxable + income_non_taxable transactions in range.
 */
income: string, 
/**
 * Sum of |amount| for spending + donation_taxable + donation_non_taxable.
 */
spending: string, 
/**
 * Period-over-period growth of `savings`-type holdings.
 */
savings_growth: string, 
/**
 * Sum of `buy` investment events in range.
 */
new_cash_invested: string, 
/**
 * Range-aware investment performance (total/market growth, start/end value).
 */
investment_metrics: InvestmentMetrics, };
