// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hierarchical category entry.
 */
export type Category = { id: string, name: string, parent_id: string | null, display_order: number, is_active: boolean, created_at: string, updated_at: string, };
