// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryType } from "./CategoryType";

/**
 * Tree node used in `GET /api/categories` response.
 */
export type CategoryNode = { id: string, name: string, 
/**
 * Optional free-text description. Same role as on `Category`.
 */
description: string | null, category_type: CategoryType, children: Array<CategoryNode>, };
