// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate spend per category, used by `GET /api/transactions/by-category`.
 */
export type CategoryTotal = { category: string, 
/**
 * Signed sum of `amount` for this category (negative = net spend).
 */
total: string, };
