// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tree node used in `GET /api/categories` response.
 */
export type CategoryNode = { id: string, name: string, children: Array<CategoryNode>, };
