// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate spend per category, used by `GET /api/transactions/by-category`.
 */
export type CategoryTotal = { category: string, 
/**
 * When `direction` is unset the total is the signed net sum
 * (negative = net spend). When `direction` is `outflow` or `income`
 * the total is the sum of absolute values of matching transactions.
 */
total: string, };
