// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic classification of a category, used to drive filtering and the
 * income/spending/transfer logic across budgets, charts and the portfolio
 * card. Every category has exactly one;
 */
export type CategoryType = "spending" | "income_taxable" | "income_non_taxable" | "interest_taxable" | "interest_non_taxable" | "internal_transfer" | "donation_taxable" | "donation_non_taxable";
