// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryType } from "./CategoryType";

/**
 * A hierarchical category entry.
 */
export type Category = { id: string, name: string, parent_id: string | null, display_order: number, is_active: boolean, 
/**
 * Optional free-text description. Surfaced to LLM categorisation agents
 * to disambiguate categories that share similar names (e.g. "Bills:
 * utility bills like internet, water, electricity" vs "Subscriptions").
 */
description: string | null, category_type: CategoryType, created_at: string, updated_at: string, };
