// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a transaction's category came from. Phase 1 only writes `Rule`
 * from CSV imports and `Manual` from CLI category edits; `Agent` is
 * reserved for data pushed in by external AI agents in later phases.
 */
export type CategorySource = "rule" | "agent" | "manual";
