// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CgtRealizedEvent } from "./CgtRealizedEvent";

/**
 * A single real-world disposal, with HMRC's matching-rule buckets rolled back up.
 *
 * `realized_events` emits one row per **matched bucket** — a sale of 500 shares that matches
 * 100 same-day + 50 under the 30-day rule + 350 from the S104 pool becomes three rows, because
 * the matching rules force three different cost-basis calculations. But nobody sold three
 * times, and SA108 box 23 ("number of disposals") wants the honest count. This groups by
 * `(symbol, disposal_date)` — the actual sale — and sums the constituent matches back together.
 *
 * Deliberately NOT grouped by `rule_applied` (that's what `realized_events` already gives you —
 * it would just re-introduce the same artifact) and NOT by rate band (a tax-computation concern,
 * out of scope here — see plan 23 §7.7).
 */
export type CgtDisposalGroup = { symbol: string, disposal_date: string, quantity: string, proceeds: string, cost_basis: string, gain_loss: string, 
/**
 * Source metadata only — the currency the constituent trades were denominated
 * in. **Not a formatting label**: `proceeds`, `cost_basis` and `gain_loss` above
 * are all in the preferred base currency (GBP). See
 * [`CgtRealizedEvent::original_currency`].
 *
 * Every event in a group provably shares one currency:
 * `check_single_currency_per_symbol` rejects a symbol carrying more than one
 * before the engine runs, and a group never spans symbols.
 */
original_currency: string, 
/**
 * The individual matched-bucket rows this group rolls up. Same objects as in
 * `realized_events` (by `disposal_id` + `rule_applied`), repeated here so a
 * consumer that only fetched `disposal_groups` can still show the breakdown.
 */
events: Array<CgtRealizedEvent>, };
