// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CgtMatchDetail = { acquisition_id: string | null, acquisition_date: string | null, quantity: string, price: string, };
