// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CgtMatchDetail } from "./CgtMatchDetail";

export type CgtRealizedEvent = { symbol: string, disposal_id: string, disposal_date: string, quantity: string, 
/**
 * The traded price per share, in [`Self::original_currency`]. This is the one
 * money field on this struct that is genuinely native — it is `price_per_share`
 * straight off the event, never converted.
 */
disposal_price: string, proceeds: string, cost_basis: string, 
/**
 * `proceeds - cost_basis`, and therefore in base currency (GBP) like both.
 */
gain_loss: string, rule_applied: string, 
/**
 * Source metadata only: the currency the underlying trade was denominated in.
 *
 * **It is NOT a formatting label for the money on this struct.** `proceeds`,
 * `cost_basis` and `gain_loss` are all converted to the preferred base currency
 * (GBP) before serialisation, so formatting them with this field renders a GBP
 * amount behind a "$". That exact bug has now been found three separate times —
 * here, on [`S104PoolState`], and latently on [`CgtDisposalGroup`] — because the
 * name reads like a display currency. Only [`Self::disposal_price`] is native.
 *
 * Use it the way `cgt_per_symbol_table.tsx` does: as a non-formatting badge shown
 * when it differs from base.
 */
original_currency: string, matches: Array<CgtMatchDetail>, };
