// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CgtMatchDetail } from "./CgtMatchDetail";

export type CgtRealizedEvent = { symbol: string, disposal_id: string, disposal_date: string, quantity: string, disposal_price: string, proceeds: string, cost_basis: string, gain_loss: string, rule_applied: string, original_currency: string, matches: Array<CgtMatchDetail>, };
