// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChecklistStatus } from "./ChecklistStatus";

/**
 * One row in the ingestion checklist for a given month.
 */
export type ChecklistItem = { account_id: string, account_name: string, status: ChecklistStatus, completed_at: string | null, notes: string | null, };
