// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExchangeRateInput } from "./ExchangeRateInput";

/**
 * Request body for POST /api/exchange-rates.
 *
 * Always a batch: a report needs ~49 rates for a single tax year, so bulk
 * entry is the normal case rather than the exception. A single rate is just a
 * batch of one.
 */
export type CreateExchangeRatesPayload = { rates: Array<ExchangeRateInput>, };
