// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateInvestmentEventBody = { account_id: string, event_type: string, symbol: string, date: string, quantity: string, price_per_share: string, fee: string | null, currency: string, 
/**
 * ISO 4217 currency of the fee when it differs from `currency`. Omit / `None`
 * to charge the fee in the trade currency; the server defaults it to
 * `currency` whenever a fee is present.
 */
fee_currency: string | null, notes: string | null, 
/**
 * IDs of the source documents this row was extracted from (`documents.id`).
 * The parse endpoint fills these in per row; manual rows leave it empty.
 */
source_document_ids: Array<string>, };
