// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A currency in use in the app. Returned by GET /api/currencies.
 */
export type Currency = { code: string, is_preferred: boolean, fx_rate: string, updated_at: string | null, };
