// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One prior tax year's contribution to a derived brought-forward loss figure.
 */
export type DerivedLossYear = { 
/**
 * `YYYY-YY`.
 */
tax_year: string, 
/**
 * Net loss remaining after that year's own gains. Always > 0: years that
 * netted to a gain contribute nothing and are omitted.
 */
net_loss: string, };
