// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivedLossYear } from "./DerivedLossYear";

/**
 * A *suggested* brought-forward loss figure, derived from prior-year losses
 * already in the ledger.
 *
 * Deliberately shaped so a consumer cannot render it as a settled number. It
 * carries the years it was built from and an explicit caveat, because the
 * derivation is knowably incomplete: UK capital losses carry forward only if
 * they were CLAIMED within four years of the end of the tax year they arose
 * in, and only the excess left after setting them against that same year's
 * gains carries at all. This app cannot see whether a claim was made, so the
 * figure can only ever OVERSTATE. It is a prefill for a field the user
 * confirms, never a value to store on the user's behalf.
 */
export type DerivedBroughtForwardLosses = { 
/**
 * Sum of `contributions`. Always >= 0.
 */
amount: string, 
/**
 * Per-year breakdown, earliest first, so the UI can show its working.
 */
contributions: Array<DerivedLossYear>, 
/**
 * Machine-readable statement that this is an upper bound, not a fact.
 */
is_upper_bound: boolean, };
