// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attached to aggregated monetary values when all source amounts share the
 * same non-preferred currency. Lets the frontend show the original-currency
 * value alongside the converted preferred-currency value.
 */
export type DisplayCurrency = { value: string, currency: string, };
