// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API view of a stored document: metadata plus how many rows reference it.
 */
export type DocumentSummary = { id: string, filename: string, mime_type: string, size_bytes: number, origin: string, account_id: string | null, uploaded_at: string, 
/**
 * Total rows across transactions + holdings + investments linking this doc.
 */
reference_count: number, 
/**
 * True when `reference_count == 0`, regardless of `origin`.
 */
orphaned: boolean, };
