// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-entity reference counts for one document. Used in the delete-conflict
 * body and the force-delete unlink summary.
 */
export type DocumentReferences = { transactions: number, holdings: number, investments: number, };
