// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentReferences } from "./DocumentReferences";

/**
 * Response from a successful `DELETE /api/documents/:id` (force or unreferenced).
 */
export type DocumentDeleteResult = { deleted: boolean, unlinked: DocumentReferences, };
