// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParserCallCost } from "./ParserCallCost";

/**
 * Per-call breakdown plus total for a parse run.
 */
export type EstimatedPrice = { calls: Array<ParserCallCost>, total: string, currency: string, };
