// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A date-keyed exchange rate. Returned by GET /api/exchange-rates.
 *
 * `rate` is the number of `quote` units per ONE `base` unit, so
 * `amount_in_quote = amount_in_base * rate`. A row
 * `(base: "USD", quote: "GBP", rate: "0.7862")` means $1 = £0.7862.
 * The direction is restated on every type that carries a rate because an
 * inverted rate yields plausible-looking but wrong tax figures.
 */
export type ExchangeRate = { base: string, quote: string, 
/**
 * YYYY-MM-DD.
 */
date: string, rate: string, 
/**
 * Provenance: "user" (typed in) or "suggested" (pre-filled then accepted).
 */
source: string, updated_at: string | null, };
