// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rate in a bulk create/update request.
 */
export type ExchangeRateInput = { base: string, 
/**
 * Defaults to the preferred currency when omitted, which is what the
 * pre-flight screen wants — every rate it collects quotes into the
 * currency the report is denominated in.
 */
quote: string | null, 
/**
 * YYYY-MM-DD.
 */
date: string, rate: string, 
/**
 * Defaults to "user".
 */
source: string | null, };
