// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { ParseMode } from "./ParseMode";

/**
 * **EXPERIMENTAL — testing only, not for production use.** Opt-in knobs for
 * trying alternative parsing strategies and model agents. The web UI never
 * sends this; omitting it runs the default unified pipeline. Kept on the API
 * surface so split mode and specific model agents can be exercised by tests
 * and ad-hoc scripts.
 */
export type ExperimentalParseOptions = { mode: ParseMode, 
/**
 * Override every LLM call's model. `None` uses per-parser defaults.
 */
agent: Agent | null, };
