// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { ParseMode } from "./ParseMode";

/**
 * **EXPERIMENTAL.** Opt-in knobs for trying alternative parsing strategies
 * and model agents. May be renamed or removed once the unified-mode
 * prototype is promoted or dropped.
 */
export type ExperimentalParseOptions = { mode: ParseMode, 
/**
 * Override every LLM call's model. `None` uses per-parser defaults.
 */
agent: Agent | null, };
