// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time granularity used by spending-grid and portfolio-history endpoints.
 */
export type Granularity = "monthly" | "quarterly" | "yearly";
