// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayCurrency } from "./DisplayCurrency";

/**
 * One row in the `GET /api/holdings/cash-flow` response.
 */
export type HoldingsCashFlowMonth = { 
/**
 * Period label: "YYYY-MM", "YYYY-Qn", or "YYYY".
 */
month: string, income: string, income_display: DisplayCurrency | null, spending: string, spending_display: DisplayCurrency | null, };
