// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { BreakdownItem } from "./BreakdownItem";
import type { InvestmentMetrics } from "./InvestmentMetrics";

/**
 * Full holdings summary returned by `GET /api/holdings/summary`.
 */
export type HoldingsSummaryResponse = { net_worth: string, currency: string, 
/**
 * ISO 8601 date the response was computed for (the `as_of` parameter or today).
 */
as_of: string, total_assets: string, total_liabilities: string, 
/**
 * Sum of checking, savings, investment, cash, and credit accounts.
 */
available_wealth: string, 
/**
 * Sum of pension (and future: property) accounts.
 */
unavailable_wealth: string, 
/**
 * All accounts with carry-forward balances. `is_stale` set per account.
 */
accounts: Array<Account>, by_type: Array<BreakdownItem>, by_institution: Array<BreakdownItem>, by_asset_class: Array<BreakdownItem>, investment_metrics: InvestmentMetrics, };
