// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingType } from "./HoldingType";

export type Holding = { account_id: string, symbol: string, name: string, holding_type: HoldingType, quantity: string, price_per_unit: string | null, value: string, currency: string, as_of: string, short_name: string | null, sub_account: string | null, is_closed: boolean, };
