// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HoldingPreview = { account_id: string, symbol: string, sub_account: string | null, value: string, currency: string, as_of: string, status: string, existing_value: string | null, 
/**
 * True when the underlying snapshot was computed/inferred rather than
 * read directly from the source document. Drives the "Source" badge in
 * the import preview. Always `false` for previews that did not come from
 * the LLM extraction pipeline (e.g. the user-driven /api/holdings preview).
 */
derived: boolean, };
