// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HoldingPreview = { account_id: string, symbol: string, sub_account: string | null, value: string, currency: string, as_of: string, status: string, existing_value: string | null, };
