// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotPeriod } from "./SnapshotPeriod";

export type HoldingsReturnConfig = { enabled: boolean, period: SnapshotPeriod | null, };
