// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingPreview } from "./HoldingPreview";
import type { HoldingsImportPayload } from "./HoldingsImportPayload";

export type HoldingsIngestionResult = { count: number, new: number, modify: number, rows: Array<HoldingPreview>, payload: HoldingsImportPayload | null, };
