// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Holding } from "./Holding";

export type HoldingsImportPayload = { account_id: string, holdings: Array<Holding>, };
