// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingType } from "./HoldingType";

/**
 * One holding in a write request. The amount is a presence-discriminated union:
 * supply either `value` (scalar: cash, property, loan, credit) OR both
 * `quantity` and `price_per_unit` (computed: stock, etf, fund, bond, crypto),
 * never both. The backend derives `value = quantity * price_per_unit` for the
 * computed arm. The response `Holding` stays flat so reads never branch.
 */
export type HoldingWrite = { symbol: string, name: string, holding_type: HoldingType, currency: string, as_of: string, sub_account: string | null, is_closed: boolean, source_document_ids: Array<string>, value: string | null, quantity: string | null, price_per_unit: string | null, };
