// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingType } from "./HoldingType";

export type Holding = { account_id: string, symbol: string, name: string, holding_type: HoldingType, quantity: string, price_per_unit: string | null, value: string, currency: string, as_of: string, short_name: string | null, sub_account: string | null, is_closed: boolean, 
/**
 * Import-time provenance: `true` when this snapshot was computed/inferred
 * from other data (e.g. interpolated from transactions or neighbouring
 * period balances), `false` when read directly from the source document.
 * Not persisted to SQLite; surfaces in the import preview only and
 * defaults to `false` when round-tripped through the API or read back.
 */
derived: boolean, };
