// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingPreview } from "./HoldingPreview";
import type { HoldingsImportPayload } from "./HoldingsImportPayload";
import type { KnownHolding } from "./KnownHolding";

export type HoldingsIngestionResult = { count: number, new: number, modify: number, rows: Array<HoldingPreview>, payload: HoldingsImportPayload | null, 
/**
 * Latest open snapshot per distinct (symbol, sub_account) already on this
 * account in the DB. Drives the Holdings preview's symbol picker
 * (autocomplete vs free-text) and the "vs prev" diff column on each row.
 * Empty when the account has no holdings yet.
 */
known_holdings: Array<KnownHolding>, };
