// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingWrite } from "./HoldingWrite";

/**
 * Request body for the holdings write endpoints (`POST /api/holdings/import`
 * and `POST /api/holdings/:account_id`). See [`HoldingWrite`] for the union.
 */
export type HoldingsWritePayload = { account_id: string, holdings: Array<HoldingWrite>, };
