// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategorySource } from "./CategorySource";

/**
 * Input record for `POST /api/import` (structured JSON from external agents).
 */
export type ImportTransaction = { date: string, description: string, amount: string, currency: string | null, 
/**
 * FK to categories.id (leaf node)
 */
category_id: string | null, category_source: CategorySource | null, notes: string | null, is_recurring: boolean | null, exclude_from_summary: boolean | null, 
/**
 * IDs of the source documents this row was extracted from (`documents.id`).
 * The parse endpoint fills these in per row; manual rows leave it empty.
 */
source_document_ids: Array<string>, };
