// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportTransaction } from "./ImportTransaction";

/**
 * Request body for `POST /api/import`.
 */
export type ImportPayload = { account_id: string, transactions: Array<ImportTransaction>, };
