// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankFormat } from "./BankFormat";
import type { ImportRowError } from "./ImportRowError";

/**
 * Aggregated result of one file or payload import.
 */
export type ImportResult = { rows_total: bigint, rows_inserted: bigint, rows_duplicate: bigint, filename: string, account_id: string, 
/**
 * Bank detected by the LLM parser. `Unknown` if unrecognised or not yet
 * set (e.g. in the aggregated totals object in the CLI).
 */
detected_bank: BankFormat, 
/**
 * LLM's own confidence in `detected_bank` [0.0, 1.0]. Zero for the
 * synthetic totals row produced by the CLI.
 */
detection_confidence: number, 
/**
 * Per-row errors from a partial-success import (API path only).
 */
errors: Array<ImportRowError>, };
