// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-row error detail in a partial-success import response.
 */
export type ImportRowError = { 
/**
 * Zero-based index into the `transactions` array.
 */
index: number, reason: string, };
