// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategorySource } from "./CategorySource";

/**
 * Input record for `POST /api/import` (structured JSON from external agents).
 */
export type ImportTransaction = { date: string, description: string, amount: string, currency: string | null, category: string | null, category_source: CategorySource | null, notes: string | null, is_recurring: boolean | null, };
