// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClarificationRequest } from "./ClarificationRequest";
import type { HoldingsIngestionResult } from "./HoldingsIngestionResult";
import type { IngestionMetadata } from "./IngestionMetadata";
import type { IngestionStatus } from "./IngestionStatus";
import type { InvestmentIngestionResult } from "./InvestmentIngestionResult";
import type { TransactionIngestionResult } from "./TransactionIngestionResult";

/**
 * Top-level response from `POST /api/parse` (Stage 1).
 */
export type IngestionPreview = { status: IngestionStatus, metadata: IngestionMetadata, transactions: TransactionIngestionResult, holdings: HoldingsIngestionResult, investments: InvestmentIngestionResult, clarifications_needed: Array<ClarificationRequest>, };
