// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EstimatedPrice } from "./EstimatedPrice";

export type IngestionMetadata = { files_processed: number, institution_detected: string | null, detection_confidence: number, processing_time_ms: bigint, notes: Array<string>, relationships_found: Array<string>, estimated_price: EstimatedPrice, };
