// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvestmentImportError } from "./InvestmentImportError";

export type InvestmentImportResult = { total: number, inserted: number, duplicates: number, errors: Array<InvestmentImportError>, };
