// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionPreviewStatus } from "./TransactionPreviewStatus";

export type InvestmentPreviewRow = { index: number, event_type: string, symbol: string, date: string, quantity: string, price_per_share: string, currency: string, status: TransactionPreviewStatus, 
/**
 * Why this row was rejected, when `status` is `Error` (e.g. low confidence,
 * invalid date/quantity/price). `None` for new/duplicate rows.
 */
error_reason?: string, existing_id: string | null, 
/**
 * IDs of the source documents this row was extracted from (resolve names
 * via `IngestionPreview.documents`).
 */
source_document_ids: Array<string>, };
