// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvestmentEventType } from "./InvestmentEventType";

export type InvestmentEvent = { id: string, account_id: string, event_type: InvestmentEventType, symbol: string, date: string, quantity: string, price_per_share: string, fee: string | null, currency: string, notes: string | null, fingerprint: string, created_at: string, 
/**
 * IDs of the source documents this event was extracted from
 * (`documents.id`). Empty for manual / API imports.
 */
source_document_ids: Array<string>, };
