// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvestmentPreviewRow } from "./InvestmentPreviewRow";
import type { InvestmentsImportPayload } from "./InvestmentsImportPayload";

export type InvestmentIngestionResult = { count: number, new: number, duplicate: number, rows: Array<InvestmentPreviewRow>, payload: InvestmentsImportPayload | null, };
