// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Investment performance metrics included in `GET /api/portfolio`.
 */
export type InvestmentMetrics = { start_value: string, end_value: string, 
/**
 * `end_value - start_value`
 */
total_growth: string, 
/**
 * Net cash moved into investment accounts over the period (positive = in).
 */
new_cash_invested: string, 
/**
 * `total_growth - new_cash_invested` (pure price appreciation).
 */
market_growth: string, };
