// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateInvestmentEventBody } from "./CreateInvestmentEventBody";

export type InvestmentsImportPayload = { account_id: string, events: Array<CreateInvestmentEventBody>, };
