// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One period in the `GET /api/investments/history` response. Both values are
 * `null` where the period has no underlying data (before the first
 * contribution event, or no active holdings) so the chart shows a gap rather
 * than a phantom zero. Values are decimal strings in the preferred currency.
 */
export type InvestmentHistoryRow = { 
/**
 * Period label: "YYYY-MM" / "YYYY-Qn" / "YYYY".
 */
period: string, 
/**
 * Cumulative net contributions (buys/vests/transfers in, sells/withholds out, plus fees).
 */
net_invested: string | null, 
/**
 * Market value of all active investment + ISA holdings.
 */
market_value: string | null, };
