// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingType } from "./HoldingType";

/**
 * Compact summary of an account's most recent open snapshot for a given
 * `(symbol, sub_account)`. Sent on the holdings preview response so the
 * frontend can offer existing symbols as suggestions and show diff-from-prev
 * without a second round-trip.
 */
export type KnownHolding = { symbol: string, name: string, holding_type: HoldingType, currency: string, sub_account: string | null, 
/**
 * Last value for this holding as a decimal string.
 */
last_value: string, 
/**
 * ISO date of the last snapshot (`YYYY-MM-DD`).
 */
last_as_of: string, };
