// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `(currency, date)` pair with no stored rate.
 */
export type MissingRatePair = { currency: string, 
/**
 * YYYY-MM-DD.
 */
date: string, };
