// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingRatePair } from "./MissingRatePair";

/**
 * The structured payload behind a `missing_exchange_rates` error.
 */
export type MissingExchangeRates = { 
/**
 * The currency every missing rate must be quoted into — the preferred currency.
 */
quote: string, missing: Array<MissingRatePair>, };
