// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic pagination envelope shared by list endpoints. `total` is the full
 * match count across all pages; `data` holds the current page.
 */
export type Paginated<T> = { data: Array<T>, total: number, page: number, limit: number, };
