// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReturnType } from "./ReturnType";

export type ParseHints = { return_type: ReturnType, hint: string | null, };
