// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExperimentalParseOptions } from "./ExperimentalParseOptions";
import type { ReturnType } from "./ReturnType";

export type ParseHints = { return_type: ReturnType, 
/**
 * **EXPERIMENTAL.** Opt-in. See [`ExperimentalParseOptions`].
 */
experimental: ExperimentalParseOptions | null, 
/**
 * Free-text hint surfaced to every parser's prompt verbatim.
 */
hint: string | null, };
