// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";

/**
 * Cost of a single LLM call made during a parse run.
 */
export type ParserCallCost = { 
/**
 * Parser id, e.g. "csv_transactions", "pdf_holdings", "unified".
 */
parser: string, agent: Agent, model: string, input_tokens: bigint, output_tokens: bigint, duration_ms: bigint, amount: string, 
/**
 * Always "USD". Frontend converts for display.
 */
currency: string, };
