// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParsePhase = "preprocessing" | "building_context" | "sending_to_llm" | "waiting_for_llm" | "post_processing";
