// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchInvestmentEventBody = { event_type: string | null, symbol: string | null, date: string | null, quantity: string | null, price_per_share: string | null, fee: string | null, currency: string | null, fee_currency: string | null, notes: string | null, };
