// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the `GET /api/portfolio/history` response.
 */
export type PortfolioHistoryRow = { 
/**
 * Period label: "YYYY-MM" for monthly, "YYYY-Qn" for quarterly, "YYYY" for yearly.
 */
month: string, available_wealth: string, unavailable_wealth: string, total_wealth: string, };
