// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A profile represents one person in a multi-person household.
 */
export type Profile = { id: string, name: string, 
/**
 * HMRC Unique Taxpayer Reference (10 digits), used on SA108 pages of a
 * generated CGT report. `None` until the user supplies one.
 */
utr: string | null, };
