// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsePhase } from "./ParsePhase";

export type ProgressEvent = { "event": "phase", phase: ParsePhase, message: string, task_id: string | null, } | { "event": "llm_start", model: string, input_tokens: number, task_id: string | null, } | { "event": "llm_progress", output_tokens: number, elapsed_ms: number, 
/**
 * Rows extracted so far, derived live from the streamed tool JSON.
 */
items: number, 
/**
 * Section being extracted: "transactions" | "holdings" | "investments".
 */
section: string | null, task_id: string | null, } | { "event": "done", total_ms: number, } | { "event": "error", code: string, message: string, };
