// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for PUT /api/tax-inputs/:profile_id/:tax_year.
 */
export type PutTaxInputsPayload = { brought_forward_losses: string | null, allowable_income_remaining: string | null, aea_claimed: boolean | null, };
