// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaxConfigEntryInput } from "./TaxConfigEntryInput";

/**
 * Request body for PUT /api/tax-config: the complete set of entries for one
 * tax year, replacing whatever is stored for it.
 *
 * Replace rather than merge, because the entries for a year are a *set* that
 * must tile it: a partial update could leave a gap between two rate bands, and
 * a disposal falling in that gap would silently go untaxed.
 */
export type PutTaxConfigPayload = { tax_year: string, entries: Array<TaxConfigEntryInput>, };
