// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingsReturnConfig } from "./HoldingsReturnConfig";

export type ReturnType = { transactions: boolean, holdings: HoldingsReturnConfig, investments: boolean, };
