// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type S104PoolState = { symbol: string, current_shares: string, total_allowable_expenditure: string, average_cost_per_share: string, };
