// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type S104PoolState = { symbol: string, 
/**
 * Native currency of `total_allowable_expenditure` and `average_cost_per_share`, which are
 * held in the symbol's own currency rather than the preferred one. Mandatory on purpose: a
 * pool always has at least one event to read it from, and making it optional would push the
 * ambiguity onto every consumer — which is the bug it exists to fix, since a symbol sitting
 * in the pool with no disposals in the window would otherwise be rendered against the base
 * currency and silently mislabelled.
 */
original_currency: string, current_shares: string, total_allowable_expenditure: string, average_cost_per_share: string, };
