// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Maps one budget category to a spending-grid section.
 */
export type SectionMapping = { 
/**
 * One of: Income | Bills | Spending | Irregular | Transfers
 */
section: string, category: string, };
