// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/budget/override`. Sets a per-month override
 * on top of the standing budget for one category.
 */
export type SetBudgetOverrideBody = { month: string, category: string, amount: string, };
