// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /api/budget`. Sets a standing monthly target
 * for one category that applies to every month unless overridden.
 */
export type SetStandingBudgetBody = { category: string, amount: string, };
