// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Start/end balance delta for one account. Used by `GET /api/portfolio/snapshots?summary=true`.
 */
export type SnapshotDelta = { account_id: string, start_balance: string | null, end_balance: string | null, delta: string | null, };
