// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the spending-grid response. `periods` maps period strings
 * (e.g. "2026-01", "2026-Q1", "2026") to the spending total as a Decimal
 * string, or null if there were no transactions in that period.
 */
export type SpendingGridRow = { category: string, section: string, 
/**
 * Period key -> decimal string (or null). Amounts are signed:
 * negative = expense, positive = income/credit.
 */
periods: Record<string, string | null>, 
/**
 * Average spend per period that had any transactions.
 */
average: string | null, 
/**
 * Standing budget amount for this category (decimal string).
 */
budget: string | null, 
/**
 * Sum across all periods.
 */
total: string | null, };
