// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A standing monthly budget target for one category.
 */
export type StandingBudget = { 
/**
 * Legacy display name (kept for backward compat)
 */
category: string | null, 
/**
 * FK to categories.id (leaf)
 */
category_id: string | null, amount: string, };
