// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A standing monthly budget target for one category.
 */
export type StandingBudget = { category: string, amount: string, };
