// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SymbolSummary = { symbol: string, total_proceeds: string, total_allowable_costs: string, total_gains: string, total_losses: string, net_gain_loss: string, original_currency: string, };
