// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rate band's contribution to the computation.
 *
 * A band is a (period, rate_kind) pair: 2024-25 produces up to four, because
 * the Autumn Budget 2024 changed the rates mid-year. Gains are assigned to a
 * band by `disposal_date`, and deductions are taken from the HIGHEST-RATE band
 * first, which is the taxpayer-favourable order HMRC's own computation uses.
 */
export type TaxBandResult = { 
/**
 * Inclusive `YYYY-MM-DD` bounds of the period this band covers.
 */
valid_from: string, valid_to: string, 
/**
 * `basic` or `higher`.
 */
rate_kind: string, 
/**
 * The rate applied, as a decimal fraction (0.24, not 24).
 */
rate: string, 
/**
 * Gains falling in this band before any deduction.
 */
gains: string, 
/**
 * Losses and AEA taken off this band.
 */
deductions: string, 
/**
 * `gains - deductions`, never negative.
 */
taxable: string, 
/**
 * `taxable * rate`, rounded to 2dp.
 */
tax: string, };
