// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One statutory tax parameter for a tax year: either the Annual Exempt Amount
 * or one capital gains rate band.
 *
 * A tax year normally carries one band per `rate_kind`. 2024-25 carries two,
 * because the Autumn Budget 2024 raised CGT on shares from 10%/20% to 18%/24%
 * on 30 October 2024. That mid-year change is represented as two ordinary rows
 * with adjacent `valid_from`/`valid_to` ranges, so the computation buckets
 * disposals by date against whatever bands exist and needs no special case for
 * that year and no code change for the next Budget.
 */
export type TaxConfigEntry = { 
/**
 * `YYYY-YY`, e.g. `2024-25`.
 */
tax_year: string, 
/**
 * `aea` or `rate`.
 */
kind: string, 
/**
 * `basic` or `higher` when `kind == "rate"`; empty string for `aea`.
 */
rate_kind: string, 
/**
 * Inclusive `YYYY-MM-DD` lower bound of the period this entry applies to.
 */
valid_from: string, 
/**
 * Inclusive `YYYY-MM-DD` upper bound.
 */
valid_to: string, 
/**
 * The allowance, in the base currency. Present when `kind == "aea"`.
 */
amount: string | null, 
/**
 * A decimal fraction, so 24% is `0.24`. Present when `kind == "rate"`.
 */
rate: string | null, updated_at: string | null, };
