// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a PUT /api/tax-config body. `tax_year` is taken from the
 * enclosing payload rather than repeated per entry.
 */
export type TaxConfigEntryInput = { kind: string, rate_kind: string | null, valid_from: string, valid_to: string, amount: string | null, rate: string | null, };
