// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaxBandResult } from "./TaxBandResult";
import type { TaxInputs } from "./TaxInputs";

/**
 * The computed Capital Gains Tax figure for one tax year, with its working shown.
 *
 * Every intermediate step is a field rather than a comment, because this number
 * ends up on a document a user may file. A single `tax_due` scalar would be
 * impossible to check against HMRC's own worked example, and impossible to
 * argue with when it disagrees.
 */
export type TaxComputation = { 
/**
 * `YYYY-YY`.
 */
tax_year: string, 
/**
 * The rate bands the year was split into, earliest first, each carrying the
 * gains that fell in it and the tax charged on them.
 */
bands: Array<TaxBandResult>, 
/**
 * Total chargeable gains before any deduction — the sum of positive
 * disposals across all bands.
 */
total_gains: string, 
/**
 * Losses arising in this tax year, applied before the AEA.
 */
current_year_losses_applied: string, 
/**
 * Brought-forward losses actually used. Can be less than the figure held in
 * `tax_inputs`: losses are only used down to the point where the remaining
 * gain is covered by the AEA, and the rest stays carried forward.
 */
brought_forward_losses_applied: string, 
/**
 * Brought-forward losses left over to carry into the next year.
 */
brought_forward_losses_remaining: string, 
/**
 * The Annual Exempt Amount actually applied. Zero when `aea_claimed` is
 * false, and otherwise capped at the gains remaining after losses.
 */
aea_applied: string, 
/**
 * Gains left chargeable after losses and the AEA.
 */
taxable_gain: string, 
/**
 * The bottom line: sum of `tax` across `bands`.
 */
tax_due: string, 
/**
 * The inputs this computation was run with, echoed back so a stored report
 * records the assumptions it was generated under.
 */
inputs: TaxInputs, };
