// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One taxpayer's own figures for a tax year. Nothing here is statutory and
 * nothing here is derivable from the ledger alone.
 */
export type TaxInputs = { profile_id: string, 
/**
 * `YYYY-YY`, e.g. `2024-25`.
 */
tax_year: string, 
/**
 * Unused allowable losses carried in from earlier years. User-entered: a
 * derived figure is offered as a prefill but never stored automatically,
 * because losses carry forward only if claimed in time and only net of
 * the arising year's own gains.
 */
brought_forward_losses: string, 
/**
 * Unused headroom in the taxpayer's basic-rate INCOME tax band. Gains up
 * to this amount are charged at the basic CGT rate, the rest at the
 * higher rate. Not derivable, since this app does not see PAYE income, so
 * it defaults to 0, meaning every gain is charged at the higher rate.
 */
allowable_income_remaining: string, 
/**
 * Whether to apply the Annual Exempt Amount at all. Claiming it is
 * optional and occasionally not worth doing.
 */
aea_claimed: boolean, updated_at: string | null, };
