// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionPreviewStatus } from "./TransactionPreviewStatus";

/**
 * A single row in a transaction dryrun preview.
 */
export type TransactionPreviewRow = { index: number, date: string, description: string, amount: string, currency: string, status: TransactionPreviewStatus, existing_id: string | null, existing_description: string | null, error_reason: string | null, };
