// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategorySource } from "./CategorySource";

/**
 * A single bank transaction.
 *
 * `amount` follows the bank convention: negative = money out, positive =
 * money in. Money is parsed into `Decimal` on the way in and serialized as
 * a string on the way out so we never touch floats.
 */
export type Transaction = { id: string, date: string, description: string, normalized: string, amount: string, currency: string, account_id: string, category: string | null, category_source: CategorySource | null, confidence: number | null, notes: string | null, is_recurring: boolean, fingerprint: string, fitid: string | null, };
