// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankFormat } from "./BankFormat";
import type { ImportPayload } from "./ImportPayload";
import type { TransactionPreviewRow } from "./TransactionPreviewRow";

/**
 * Full response from a transaction import dryrun.
 */
export type TransactionImportPreview = { account_id: string, filename: string, detected_bank: BankFormat, detection_confidence: number, rows: Array<TransactionPreviewRow>, rows_total: bigint, rows_new: bigint, rows_duplicate: bigint, rows_error: bigint, 
/**
 * Parsed payload ready for confirmation via `POST /api/import`.
 */
payload: ImportPayload, };
