// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cash-flow direction filter for aggregation endpoints.
 * `Outflow` sums absolute values of negative amounts (spending).
 * `Income` sums absolute values of positive amounts (credits).
 * When no direction is supplied the caller gets signed net sums.
 */
export type TransactionDirection = "outflow" | "income";
