// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportPayload } from "./ImportPayload";
import type { TransactionPreviewRow } from "./TransactionPreviewRow";

export type TransactionIngestionResult = { count: number, new: number, duplicate: number, errors: number, rows: Array<TransactionPreviewRow>, payload: ImportPayload | null, };
