// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of a bank statement after the LLM has normalised it.
 *
 * `amount` follows the signed convention used everywhere in fynance:
 * negative = money out (debit), positive = money in (credit).
 * Fields not present in the source file are `None`.
 */
export type UnifiedStatementRow = { date: string, description: string, amount: string, currency: string, 
/**
 * Unique transaction ID from the bank (Monzo "Transaction ID", Lloyds ref).
 */
fitid: string | null, 
/**
 * Spending category if the bank provides one (Monzo ships these).
 */
category: string | null, 
/**
 * Merchant name when distinct from `description` (Monzo "Name" column).
 */
merchant: string | null, 
/**
 * Counterparty name for peer-to-peer transfers (Revolut "Description").
 */
counterparty: string | null, 
/**
 * Transaction type as the bank names it (e.g. Revolut "Type": CARD_PAYMENT).
 */
transaction_type: string | null, 
/**
 * Running balance after this transaction, when the bank includes it.
 */
balance_after: string | null, 
/**
 * Any notes or tags on the transaction (Monzo "Notes and #tags").
 */
notes: string | null, 
/**
 * Payment reference when present (Lloyds "Transaction Reference").
 */
reference: string | null, 
/**
 * LLM's confidence that this row was correctly extracted [0.0, 1.0].
 */
row_confidence: number, };
