// Domain types matching the Rust data model from docs/design/03_data_model.md
// These will eventually be auto-generated by ts-rs from Rust structs.

export type CategorySource = "rule" | "claude" | "manual"

export type AccountType =
  | "checking"
  | "savings"
  | "investment"
  | "credit"
  | "cash"
  | "pension"
  | "property"
  | "mortgage"

export type HoldingType = "stock" | "etf" | "fund" | "bond" | "crypto"

export type IngestionStatus = "pending" | "completed" | "skipped"

export interface Profile {
  id: string
  name: string
}

export interface Transaction {
  id: string
  date: string // ISO 8601: YYYY-MM-DD
  description: string // raw merchant string
  normalized: string // cleaned for display
  amount: string // Decimal as string, negative = debit
  currency: string
  account_id: string
  category: string | null // null = uncategorized
  category_source: CategorySource | null
  confidence: number | null // 0.0..1.0, null for rule/manual
  notes: string | null
  is_recurring: boolean
  fingerprint: string
  fitid: string | null
}

export interface Account {
  id: string
  name: string
  institution: string
  type: AccountType
  currency: string
  balance: string | null // Decimal string
  balance_date: string | null // YYYY-MM-DD
  is_active: boolean
  notes: string | null
  profile_ids: string[] // owners of this account (supports joint accounts)
}

export interface Budget {
  month: string // YYYY-MM
  category: string
  amount: string // Decimal string, monthly budget cap
}

export interface Holding {
  id: number
  account_id: string
  symbol: string // ticker or ISIN
  name: string // display name
  short_name: string // nickname for legends/compact views
  holding_type: HoldingType
  quantity: string // Decimal string
  price_per_unit: string | null // Decimal string
  value: string // Decimal string
  currency: string
  as_of: string // YYYY-MM-DD
}

export interface PortfolioSnapshot {
  snapshot_date: string // YYYY-MM-DD
  account_id: string
  balance: string // Decimal string
  currency: string
}

export interface IngestionChecklistItem {
  month: string // YYYY-MM
  account_id: string
  status: IngestionStatus
  completed_at: string | null
  notes: string | null
}
